# Table: choices
# Columns:
#  id      | bigint | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  poll_id | bigint | NOT NULL
#  text    | text   | NOT NULL
# Indexes:
#  choices_pkey  | PRIMARY KEY btree (id)
#  choice_unique | UNIQUE btree (poll_id, text)
# Check constraints:
#  text_not_empty | (char_length(text) >= 1)
# Foreign key constraints:
#  choices_poll_id_fkey | (poll_id) REFERENCES polls(id) ON DELETE CASCADE
# Referenced By:
#  responses | responses_choice_id_fkey | (choice_id) REFERENCES choices(id) ON DELETE CASCADE

require 'sequel'

require_relative 'poll'
require_relative 'response'

module Models
  class Choice < Sequel::Model
    many_to_one :poll
    one_to_many :responses,
                remover: ->(response) { response.destroy },
                clearer: nil

    def before_validation
      cancel_action('Choice has no poll') unless poll
      cancel_action('Choice modified in expired poll') if poll.finished?
      super
    end

    def before_update
      cancel_action('Choices are immutable')
      super
    end

    def before_destroy
      cancel_action('Choice removed from expired poll') if poll.finished?
      super
    end

    def to_s
      text
    end
  end
end
